# Generated by Django 3.2.25 on 2024-07-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
