# Generated by Django 3.2.25 on 2024-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0006_pays_registration_secteur_typeclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_reade',
            new_name='is_read',
        ),
    ]
