# Generated by Django 3.2.25 on 2024-07-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0008_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu ou pas'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description du Type de Client'),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Type de Client'),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='ordre',
            field=models.IntegerField(null=True, verbose_name="Ordre d'Affichage"),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='sensible',
            field=models.BooleanField(null=True, verbose_name='Est Sensible'),
        ),
    ]
