# Generated by Django 3.2.25 on 2024-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0010_auto_20240704_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consentement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Consentement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fonction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est Actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Est Membre du Personnel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom d'Utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=225, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenoms',
            field=models.CharField(max_length=255, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone'),
        ),
    ]
