# Generated by Django 3.2.25 on 2024-07-04 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0011_auto_20240704_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Enregistrement', 'verbose_name_plural': 'Enregistrements'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='adresse_bp',
            field=models.CharField(max_length=100, null=True, verbose_name='Boîte Postale'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='adresse_geo',
            field=models.CharField(max_length=100, null=True, verbose_name='Adresse Géographique'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='effectif',
            field=models.IntegerField(null=True, verbose_name='Effectif'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email_contact',
            field=models.CharField(max_length=100, null=True, verbose_name='Email de Contact'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gmaps_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Lien Google Maps'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edcp_apirest.pays', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='presentation',
            field=models.CharField(max_length=255, null=True, verbose_name='Présentation'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='raisonsociale',
            field=models.CharField(max_length=100, verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='rccm',
            field=models.CharField(max_length=100, null=True, verbose_name='RCCM'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='representant',
            field=models.CharField(max_length=100, verbose_name='Représentant'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edcp_apirest.secteur', verbose_name="Secteur d'Activité"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='secteur_description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description du Secteur'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='site_web',
            field=models.CharField(max_length=100, null=True, verbose_name='Site Web'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='typeclient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edcp_apirest.typeclient', verbose_name='Type de Client'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ville',
            field=models.CharField(max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
