# Generated by Django 3.2.25 on 2024-07-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0012_auto_20240704_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
    ]
