# Generated by Django 3.2.25 on 2024-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0014_auto_20240704_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmb_autorisation', models.IntegerField(null=True, verbose_name="Nombre d'autorisation")),
            ],
            options={
                'verbose_name': 'Autorisation',
                'verbose_name_plural': 'Autorisations',
            },
        ),
    ]
