# Generated by Django 3.2.25 on 2024-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0015_autorisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='autorisations',
            field=models.ManyToManyField(blank=True, to='edcp_apirest.Autorisation'),
        ),
    ]
