# Generated by Django 3.2.25 on 2024-07-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0016_registration_autorisations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='autorisations',
        ),
        migrations.DeleteModel(
            name='Autorisation',
        ),
    ]
