# Generated by Django 3.2.25 on 2024-07-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcp_apirest', '0018_autorisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorisation',
            old_name='client',
            new_name='registration',
        ),
    ]
